const defaultWidgetState = {
  topic: "Business",
  feedURL: "",
  widgetLayout: "MagazineView01",
  widgetTitle: "Widget Title",
  general: {
    widthInPixels: true,
    width: 350,
    heightInPixels: true,
    height: 400,
    // autoScroll: false,
    openLinksInNewTab: true,
    fontStyle: "Trebuchet MS, sans-serif",
    textAlignment: "AlignLeft",
    border: true,
    borderColor: "#000000",
    corner: "Square",
    padding: 5,
    spaceBetweenItems: 10,
  },
  feedTitle: {
    custom: true,
    mainTitle: "",
    // mainTitleLink: "",
    feedTitleFontSize: 16,
    feedTitleBold: false,
    feedTitleBgColor: "#ffffff",
    feedTitleFontColor: "#acadae",
  },
  feedContent: {
    displayNoOfPost: 25,
    // displayLink: true,
    // displayReadMore: false,
    contentbgColor: "#ffffff",
    showAuthorAndDate: true,
    dateFormat: "Month, DD YYYY",
    title: {
      showContentTitle: true,
      contentTitleBold: false,
      contentTitleMaxChars: 50,
      contentTitleFontSize: 14,
      contentTitleColor: "#0077b5",
    },
    description: {
      showContentDesc: true,
      contentDescBold: false,
      contentDescMaxChars: 100,
      contentDescFontSize: 12,
      contentDescColor: "#acadae",
    },
  },
};
