const sources = [
        "Gizmodo.com",
        "The Verge",
        "CNET",
        "VentureBeat",
        "Brander.ca",
        "MacRumors",
        "Wired",
        "NPR",
        "BBC News",
        "Business Insider",
        "Le Monde",
        "Slashdot.org",
        "Yahoo Entertainment",
        "Journal du geek",
        "Flightaware.engineering",
        "Barchart.com",
        "Thekitchn.com",
        "Hackaday",
        "Yanko Design",
        "Android Central",
        "The New Yorker",
        "The Bookseller",
        "Buzzfeed",
        "Time",
        "Makezine.com",
        "Pethelpful.com",
        "HuffPost",
        "Seths.blog",
        "PEOPLE",
        "Eatingwell.com",
        "A Beautiful Mess",
        "Fi-le.net",
        "Polygon",
        "Xataka.com",
        "Thespruce.com",
        "USA Today",
        "GameSpot",
        "Kk.org",
        "Boredpanda.com",
        "The Atlantic",
        "Prevention.com",
        "Spring.org.uk",
        "Men's Journal",
        "Fox News",
        "ArchDaily",
        "Food52.com",
        "Cracked.com",
        "HYPEBEAST",
        "Pitchfork",
        "\/FILM",
        "Charlotte Observer",
        "Getnews.jp",
        "Windows Central",
        "Scientific American",
        "Harvard Business Review",
        "Truckingdive.com",
        "Digitalseams.com",
        "Science Daily",
        "Des Moines Register",
        "Qcnews.com",
        "Real Simple",
        "ABC News",
        "Artofmanliness.com",
        "Github.com",
        "Maxemitchell.com",
        "Theregister.com",
        "Astroimagery.com",
        "Aboutphotography.blog",
        "Slate Magazine",
        "Rolling Stone",
        "Search Engine Journal",
        "Kaveland.no",
        "Forbes",
        "Wikihow.com",
        "Calculatedriskblog.com",
        "Default.blog",
        "Kotaku",
        "Rock Paper Shotgun",
        "Blog.google",
        "ESPN",
        "Die Zeit",
        "Gizmodo.jp"
    ]

const topics = [
        "Adventure",
        "Architecture",
        "Art",
        "Automobile",
        "Aviation",
        "Baking",
        "Book Reviews",
        "Business",
        "Christian",
        "Cyber Security",
        "DIY",
        "Dogs",
        "Education",
        "Fashion",
        "Fitness",
        "Food Recipes",
        "Gaming",
        "Gardening",
        "Happiness",
        "Health",
        "Healthy Lifestyle",
        "Insurance",
        "Interior Design",
        "Knitting",
        "Leadership",
        "Legal Law",
        "Life",
        "Lifestyle",
        "Marijuana",
        "Marketing",
        "Men",
        "Mom",
        "Movies",
        "Music",
        "Nutrition",
        "Oil and Gas",
        "Parenting",
        "Personal Development",
        "Personal Finance",
        "Photography",
        "Politics",
        "Real Estate",
        "Relationship",
        "Running",
        "SEO Tips",
        "Skin Care",
        "Small Business",
        "Spiritual",
        "Sports News",
        "Stock Market",
        "Technology",
        "Travel",
        "Women",
        "Writing",
        "Yoga"
    ]
    
export {sources, topics};